{"ast":null,"code":"\"use strict\";\n\nObject.defineProperty(exports, \"__esModule\", {\n  value: true\n});\nexports.CustomValidation = void 0;\n\nclass CustomValidation {\n  constructor(validator, negated) {\n    this.validator = validator;\n    this.negated = negated;\n  }\n\n  async run(context, value, meta) {\n    try {\n      const result = this.validator(value, meta);\n      const actualResult = await result;\n      const isPromise = result && result.then;\n      const failed = this.negated ? actualResult : !actualResult; // A promise that was resolved only adds an error if negated.\n      // Otherwise it always suceeds\n\n      if (!isPromise && failed || isPromise && this.negated) {\n        context.addError(this.message, value, meta);\n      }\n    } catch (err) {\n      if (this.negated) {\n        return;\n      }\n\n      context.addError((err instanceof Error ? err.message : err) || this.message, value, meta);\n    }\n  }\n\n}\n\nexports.CustomValidation = CustomValidation;","map":{"version":3,"sources":["C:/Projects/Dev Connector/node_modules/express-validator/src/context-items/custom-validation.js"],"names":["Object","defineProperty","exports","value","CustomValidation","constructor","validator","negated","run","context","meta","result","actualResult","isPromise","then","failed","addError","message","err","Error"],"mappings":"AAAA;;AACAA,MAAM,CAACC,cAAP,CAAsBC,OAAtB,EAA+B,YAA/B,EAA6C;AAAEC,EAAAA,KAAK,EAAE;AAAT,CAA7C;AACAD,OAAO,CAACE,gBAAR,GAA2B,KAAK,CAAhC;;AACA,MAAMA,gBAAN,CAAuB;AACnBC,EAAAA,WAAW,CAACC,SAAD,EAAYC,OAAZ,EAAqB;AAC5B,SAAKD,SAAL,GAAiBA,SAAjB;AACA,SAAKC,OAAL,GAAeA,OAAf;AACH;;AACQ,QAAHC,GAAG,CAACC,OAAD,EAAUN,KAAV,EAAiBO,IAAjB,EAAuB;AAC5B,QAAI;AACA,YAAMC,MAAM,GAAG,KAAKL,SAAL,CAAeH,KAAf,EAAsBO,IAAtB,CAAf;AACA,YAAME,YAAY,GAAG,MAAMD,MAA3B;AACA,YAAME,SAAS,GAAGF,MAAM,IAAIA,MAAM,CAACG,IAAnC;AACA,YAAMC,MAAM,GAAG,KAAKR,OAAL,GAAeK,YAAf,GAA8B,CAACA,YAA9C,CAJA,CAKA;AACA;;AACA,UAAK,CAACC,SAAD,IAAcE,MAAf,IAA2BF,SAAS,IAAI,KAAKN,OAAjD,EAA2D;AACvDE,QAAAA,OAAO,CAACO,QAAR,CAAiB,KAAKC,OAAtB,EAA+Bd,KAA/B,EAAsCO,IAAtC;AACH;AACJ,KAVD,CAWA,OAAOQ,GAAP,EAAY;AACR,UAAI,KAAKX,OAAT,EAAkB;AACd;AACH;;AACDE,MAAAA,OAAO,CAACO,QAAR,CAAiB,CAACE,GAAG,YAAYC,KAAf,GAAuBD,GAAG,CAACD,OAA3B,GAAqCC,GAAtC,KAA8C,KAAKD,OAApE,EAA6Ed,KAA7E,EAAoFO,IAApF;AACH;AACJ;;AAvBkB;;AAyBvBR,OAAO,CAACE,gBAAR,GAA2BA,gBAA3B","sourcesContent":["\"use strict\";\nObject.defineProperty(exports, \"__esModule\", { value: true });\nexports.CustomValidation = void 0;\nclass CustomValidation {\n    constructor(validator, negated) {\n        this.validator = validator;\n        this.negated = negated;\n    }\n    async run(context, value, meta) {\n        try {\n            const result = this.validator(value, meta);\n            const actualResult = await result;\n            const isPromise = result && result.then;\n            const failed = this.negated ? actualResult : !actualResult;\n            // A promise that was resolved only adds an error if negated.\n            // Otherwise it always suceeds\n            if ((!isPromise && failed) || (isPromise && this.negated)) {\n                context.addError(this.message, value, meta);\n            }\n        }\n        catch (err) {\n            if (this.negated) {\n                return;\n            }\n            context.addError((err instanceof Error ? err.message : err) || this.message, value, meta);\n        }\n    }\n}\nexports.CustomValidation = CustomValidation;\n"]},"metadata":{},"sourceType":"script"}